# docker stack deploy -c docker-compose.yml <stack name>
version: '3.5'

services:

  sandman-dns-manager:
    image: abilioesteves/sandman-dns-webhook-hook-sample:0.0.6
    ports: 
      - 7070:7070
    environment:
      - SANDMAN_DNS_TTL=1200

  sandman-dns-listener:
    image: abilioesteves/sandman-dns-webhook-client-sample:0.0.6
    ports:
      - 7071:7071
    environment:
      - SANDMAN_DNS_MANAGER_ADDRESS=sandman-dns-manager:7070
      - SANDMAN_REVERSE_PROXY_ADDRESS=0.0.0.0
      - SANDMAN_DNS_TAGS=teste1,test2,teste5